# Generated by Django 6.0.2 on 2026-02-22 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_tier', models.CharField(choices=[('BUD', 'Budget'), ('STD', 'Standard'), ('PRM', 'Premium'), ('LUX', 'Luxury')], max_length=3)),
                ('transport_choice', models.CharField(choices=[('CAB', 'Cab & Driver'), ('BUS', 'Group Bus'), ('TRN', 'Train')], max_length=3)),
                ('start_date', models.DateField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.circuit')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('BUD', 'Budget'), ('STD', 'Standard'), ('PRM', 'Premium'), ('LUX', 'Luxury')], max_length=3)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.place')),
            ],
        ),
        migrations.CreateModel(
            name='CircuitStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.circuit')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.place')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='circuit',
            name='places',
            field=models.ManyToManyField(through='bookings.CircuitStop', to='bookings.place'),
        ),
    ]
