# Generated by Django 6.0.2 on 2026-02-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_days',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='circuit',
            name='description',
            field=models.TextField(default='An amazing travel experience.'),
        ),
    ]
